name: .NET CI

on:
  push:
    branches:
      - main
    paths: ['net', '.github/workflows']
  pull_request:
    paths: ['net', '.github/workflows']

jobs:
  build:
    name: Build .NET
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6
      - name: Restore dependencies
        run: dotnet restore net
      - name: Build app
        run: dotnet build -c Release --no-restore net
      - name: Run automated tests
        run: dotnet test -c Release --no-build net