# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
    paths: ['net', '.github/workflows']

  pull_request:
    branches: [ "main" ]
    paths: ['net', '.github/workflows']


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6
    - name: Restore dependencies
      run: dotnet restore net
    - name: Build
      run: dotnet build -c Release --no-restore net
    - name: Test
      run: dotnet test -c Release --no-build --verbosity normal net
