name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and test .NET
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build database image
      run: docker build ./database -t to_mssql -f ./docker/database/Dockerfile
    - name: Run container with database
      run: docker run -p 1433:1433 to_mssql
    - name: Wait for database
      run: chmod +x tools/unix/await.sh && ./tools/unix/await.sh
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6
    - name: Restore dependencies
      run: dotnet restore net
    - name: Build
      run: dotnet build -c Release --no-restore net
    - name: Test
      run: dotnet test --environment Test -c Release --no-build --verbosity normal net
